dependencies {
    implementation project(':atlashub-shared')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
}

dependencies { implementation project(':atlashub-pay:accounts') }
