rootProject.name = 'atlashub'

// Shared
include 'atlashub-shared'

// Platform
include 'atlashub-platform'
include 'atlashub-platform:catalog'
include 'atlashub-platform:accounts'

// Infrastructure
include 'atlashub-infrastructure'
include 'atlashub-infrastructure:eventbus'
include 'atlashub-infrastructure:rate-limiter'
include 'atlashub-infrastructure:audit'

// App

include 'atlashub-platform:authentication'
include 'atlashub-main'
include 'atlashub-platform:iam'