rootProject.name = 'atlashub'

// Shared
include 'atlashub-shared'

// Pay
include 'atlashub-pay'
include 'atlashub-pay:ledger'
include 'atlashub-pay:charges'
include 'atlashub-pay:settlement'
include 'atlashub-pay:tx-query'

// Platform
include 'atlashub-platform'
include 'atlashub-platform:accounts'
include 'atlashub-platform:iam'
include 'atlashub-platform:compliance'
include 'atlashub-platform:notifications'
include 'atlashub-platform:authentication'
include 'atlashub-platform:storage'

// Infrastructure
include 'atlashub-infrastructure'
include 'atlashub-infrastructure:eventbus'
include 'atlashub-infrastructure:rate-limiter'
include 'atlashub-infrastructure:audit'
include 'atlashub-infrastructure:paystack'

// App
include 'atlashub-main'


include 'atlashub-pay:accounts'
include 'atlashub-infrastructure:anchor'
include 'atlashub-pay:splits'

// Commerce
include 'atlashub-commerce'
include 'atlashub-commerce:catalog'
include 'atlashub-commerce:inventory'
include 'atlashub-commerce:storefront'

// Accounting
include 'atlashub-accounting'
include 'atlashub-accounting:gl'
