package com.atlashub.admin.domain.valueobject;

public enum AdminPermission {
    MANAGE_ADMINS,
    GRANT_REVOKE_PERMISSIONS,
    REGENERATE_ADMIN_CODE,
    VIEW_FUNDING_RECORDS,
    VIEW_AUDIT_TRAIL,
    MANAGE_ORGANIZATIONS,
    MANAGE_SYSTEM_CONFIG,
    CATALOG_MANAGE,
    COMPLIANCE_REVIEW,
    BILLING_MANAGE,
    SYSTEM_HEALTH_VIEW
}
