apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlashub-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atlashub-app
  template:
    metadata:
      labels:
        app: atlashub-app
    spec:
      containers:
      - name: atlashub-app
        image: atlashub/app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATA_REDIS_HOST
          value: "redis"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/atlashub?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "atlashub"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "atlashub"
        - name: ATLASHUB_JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: atlashub-secrets
              key: ATLASHUB_JWT_SECRET
        volumeMounts:
        - name: firebase-secrets
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: firebase-secrets
        secret:
          secretName: atlashub-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: atlashub-app
spec:
  ports:
  - port: 8080
  selector:
    app: atlashub-app
