dependencies {
    implementation project(':atlashub-shared')
    
    // Spring Boot
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-json'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Optional: Swagger for API docs
    implementation 'io.swagger.core.v3:swagger-annotations:2.2.20'
    implementation 'org.springframework.boot:spring-boot-starter-security'
}
