plugins {
    id 'java'
}

group = 'com.atlashub'
version = '2.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Inherit standard domain, base use cases, and shared models
    implementation project(':atlashub-shared')

    // Core Spring dependencies for the adapters and services
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.security:spring-security-core'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    // Optional: Swagger for API docs
    implementation 'io.swagger.core.v3:swagger-annotations:2.2.20'

    // BCrypt
    implementation 'org.springframework.security:spring-security-crypto'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
}

test {
    useJUnitPlatform()
}