plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':atlashub-shared')
    implementation project(':atlashub-pay:charges')
    implementation project(':atlashub-pay:accounts')

    implementation 'org.springframework.boot:spring-boot-starter-web'
}

dependencies { implementation project(':atlashub-platform:identity') }
